//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITYDISTRICT
    {
        public CITYDISTRICT()
        {
            this.FIRM = new HashSet<FIRM>();
            this.FIRMBRANCH = new HashSet<FIRMBRANCH>();
        }
    
        public short ID { get; set; }
        public byte CITYID { get; set; }
        public string NAME { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual ICollection<FIRM> FIRM { get; set; }
        public virtual ICollection<FIRMBRANCH> FIRMBRANCH { get; set; }
    }
}
