//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMRESPONSIBLE
    {
        public System.Guid ID { get; set; }
        public System.Guid FIRMID { get; set; }
        public System.Guid MEMBERID { get; set; }
    
        public virtual FIRM FIRM { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
