//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMDEPARTMENTMEMBER
    {
        public FIRMDEPARTMENTMEMBER()
        {
            this.RESERVATION = new HashSet<RESERVATION>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid FIRMDEPARTMENTID { get; set; }
        public System.Guid MEMBERID { get; set; }
        public bool ISACTIVE { get; set; }
    
        public virtual FIRMDEPARTMENT FIRMDEPARTMENT { get; set; }
        public virtual MEMBER MEMBER { get; set; }
        public virtual ICollection<RESERVATION> RESERVATION { get; set; }
    }
}
