//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM
    {
        public FIRM()
        {
            this.FIRMBRANCH = new HashSet<FIRMBRANCH>();
            this.FIRMDEPARTMENT = new HashSet<FIRMDEPARTMENT>();
            this.FIRMRESPONSIBLE = new HashSet<FIRMRESPONSIBLE>();
        }
    
        public System.Guid ID { get; set; }
        public byte TYPESEKTORID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<byte> CITYID { get; set; }
        public Nullable<short> CITYDISTRICTID { get; set; }
        public string ADRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> MONDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> MONDAYSTARTDATE { get; set; }
        public Nullable<decimal> MONDAYENDDATE { get; set; }
        public Nullable<decimal> TUESDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> TUESDAYSTARTDATE { get; set; }
        public Nullable<decimal> TUESDAYENDDATE { get; set; }
        public Nullable<decimal> WEDNESDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> WEDNESDAYSTARTDATE { get; set; }
        public Nullable<decimal> WEDNESDAYENDDATE { get; set; }
        public Nullable<decimal> THURSDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> THURSDAYSTARTDATE { get; set; }
        public Nullable<decimal> THURSDAYENDDATE { get; set; }
        public Nullable<decimal> FRIDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> FRIDAYSTARTDATE { get; set; }
        public Nullable<decimal> FRIDAYENDDATE { get; set; }
        public Nullable<decimal> SATURDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> SATURDAYSTARTDATE { get; set; }
        public Nullable<decimal> SATURDAYENDDATE { get; set; }
        public Nullable<decimal> SUNDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> SUNDAYSTARTDATE { get; set; }
        public Nullable<decimal> SUNDAYENDDATE { get; set; }
        public Nullable<decimal> RESERVATIONDURATION { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual CITYDISTRICT CITYDISTRICT { get; set; }
        public virtual TYPESEKTOR TYPESEKTOR { get; set; }
        public virtual ICollection<FIRMBRANCH> FIRMBRANCH { get; set; }
        public virtual ICollection<FIRMDEPARTMENT> FIRMDEPARTMENT { get; set; }
        public virtual ICollection<FIRMRESPONSIBLE> FIRMRESPONSIBLE { get; set; }
    }
}
