//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public System.Guid ID { get; set; }
        public byte TYPERESERVATIONSTATUSID { get; set; }
        public System.Guid FIRMDEPARTMENTMEMBERID { get; set; }
        public System.Guid MEMBERID { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual FIRMDEPARTMENTMEMBER FIRMDEPARTMENTMEMBER { get; set; }
        public virtual TYPERESERVATIONSTATUS TYPERESERVATIONSTATUS { get; set; }
    }
}
