//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPESEKTOR
    {
        public TYPESEKTOR()
        {
            this.FIRM = new HashSet<FIRM>();
        }
    
        public byte ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<FIRM> FIRM { get; set; }
    }
}
