//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FIRMDEPARTMENT
    {
        public System.Guid ID { get; set; }
        public System.Guid FIRMID { get; set; }
        public Nullable<System.Guid> FIRMBRANCHID { get; set; }
        public string NAME { get; set; }
        public string FIRMNAME { get; set; }
        public string FIRMBRANCHNAME { get; set; }
        public Nullable<int> FIRMDEPARTMENTMEMBERCOUNT { get; set; }
    }
}
