//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FIRM
    {
        public System.Guid ID { get; set; }
        public byte TYPESEKTORID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<byte> CITYID { get; set; }
        public Nullable<short> CITYDISTRICTID { get; set; }
        public string ADRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> MONDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> MONDAYSTARTDATE { get; set; }
        public Nullable<decimal> MONDAYENDDATE { get; set; }
        public Nullable<decimal> TUESDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> TUESDAYSTARTDATE { get; set; }
        public Nullable<decimal> TUESDAYENDDATE { get; set; }
        public Nullable<decimal> WEDNESDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> WEDNESDAYSTARTDATE { get; set; }
        public Nullable<decimal> WEDNESDAYENDDATE { get; set; }
        public Nullable<decimal> THURSDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> THURSDAYSTARTDATE { get; set; }
        public Nullable<decimal> THURSDAYENDDATE { get; set; }
        public Nullable<decimal> FRIDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> FRIDAYSTARTDATE { get; set; }
        public Nullable<decimal> FRIDAYENDDATE { get; set; }
        public Nullable<decimal> SATURDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> SATURDAYSTARTDATE { get; set; }
        public Nullable<decimal> SATURDAYENDDATE { get; set; }
        public Nullable<decimal> SUNDAYRESERVATIONDURATION { get; set; }
        public Nullable<decimal> SUNDAYSTARTDATE { get; set; }
        public Nullable<decimal> SUNDAYENDDATE { get; set; }
        public Nullable<decimal> RESERVATIONDURATION { get; set; }
        public Nullable<System.Guid> FIRMRESPONSIBLEID { get; set; }
        public string TYPESEKTORNAME { get; set; }
        public string CITYNAME { get; set; }
        public string CITYDISTRICTNAME { get; set; }
    }
}
