//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineReservation.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MEMBER
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PASWORDRESETCODE { get; set; }
        public byte TYPEMEMBERID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string FULLNAME { get; set; }
        public string LOGINNAME { get; set; }
        public string PASWORD { get; set; }
        public bool GENDER { get; set; }
        public Nullable<System.DateTime> BIRDDATE { get; set; }
        public string PHONE { get; set; }
        public bool CANLOGIN { get; set; }
        public string TYPEMEMBERNAME { get; set; }
        public string GENDERNAME { get; set; }
    }
}
